# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool: 'localmac'
  #vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
# - script: |
#     npm install
#     npm test
#     docker build -f Dockerfile -t $(dockerId)/$(imageName) .
#     docker login -u $(dockerId) -p $pswd
#     docker push $(dockerId)/$(imageName)
#   env:
#     pswd: $(dockerPassword)

# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/TEST-RESULTS.xml'
#     testRunTitle: 'Test results for JavaScript'

# - task: PublishCodeCoverageResults@1
#   inputs: 
#     codeCoverageTool: Cobertura
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
#     reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    
- script: 'pwd'
  displayName: 'going to print the darn working directory as a test'
- script: 'hostname'
  displayName: "Try and print hostname of mac?"
- script: |
    kubectl config set-cluster cluster.local --server=https://169.45.189.35:8001 --insecure-skip-tls-verify=true
    kubectl config set-context cluster.local-context --cluster=cluster.local
    kubectl config set-credentials admin --token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoibDd0dzRiMmhqdGx3eWNiYmx0ZXEiLCJyZWFsbU5hbWUiOiJjdXN0b21SZWFsbSIsInVuaXF1ZVNlY3VyaXR5TmFtZSI6ImFkbWluIiwiaXNzIjoiaHR0cHM6Ly9teWNsdXN0ZXIuaWNwOjk0NDMvb2lkYy9lbmRwb2ludC9PUCIsImF1ZCI6ImFhNzcwNGNhMTIwZWNlN2M5NTM2NjRhNzJlMGYzMGUxIiwiZXhwIjoxNTQ0NTI3NzY2LCJpYXQiOjE1NDQ0OTg5NjYsInN1YiI6ImFkbWluIiwidGVhbVJvbGVNYXBwaW5ncyI6W119.i8BCK3TkhuExJFJrlGoQwz7VgZteyI4tKNr6JdkZfTt2_G3dATrv-qNp3yXtwl6mvGL3NTC5p3sA2Rtp-rtfyYc9NbiNcsXnWZI95mZSni9EYoj1icR_Sp7s2E_85nOSsXLfB1yUmShCHmARv_56RvLr15JYtNqsk9jMiFS3tdqECwhtZJJh6AeCp2FJQWVnv4m8bFrJcZty7WznlBSzADWV00NfBfPwwBvzp0EUvHekbcO__5vf7V0YNuzX7xQcSHGl-bv8LeRO85jnsp41LWLpCARCmG3HE-R6JOoaR2eaMb3WzQlMH7XFYaphbmAQysLzb2NmVHQq-SLXnK7_4g
    kubectl config set-context cluster.local-context --user=admin --namespace=amoynaha
    kubectl config use-context cluster.local-context
    kubectl get pods
  displayName: 'run kubectl cmds'
  